### ISSUE TITLE
Explain use_solidcam_feeds

### ISSUE THREAD

**Issue by pszturmaj** [teodoryantcheff/SolidCam-Mach3-Post#12]
Could you please explain use_solidcam_feeds variable? I'm getting correct feeds for 4th axis when it's set to NO. Sometimes if I set it to YES, the 4th axis gets very high feed rate and I couldn't find the cause of this.

**Comment by teodoryantcheff** [comment]
It's been quite some time since I last dealt with that, so you'll have to take a look at the "manual". IIRC it was a windows help file shoved somewhere under the SC directory tree.

**Comment by pszturmaj** [comment]
I already checked those help files and found nothing. It seems that you introduced this variable yourself :)
https://github.com/teodoryantcheff/SolidCam-Mach3-Post/blob/master/Mach3_4X_Y.vmid#L344 - maybe it's something about 5 axis kinematics in SC?

**Comment by teodoryantcheff** [comment]
I have no recollection whatsoever, to be honest... Maybe, as you say I did add this variable.
