### ISSUE TITLE
Questions about usage.

### ISSUE THREAD

**Issue by rvega** [teodoryantcheff/SolidCam-Mach3-Post#5]
First of all. Thanks for sharing this :)

I have modeled a part in solidworks and I have access to a CNC machine controled by Mach3 software. See [this video](https://www.youtube.com/watch?v=7NTRUOdFMAU) for what I'm trying to do.
If I understand correctly. To use this postprocessor. I need to install it as instructed in the readme file, choose the Mach3 machine in solidcam and then export the Gcode.

Is there a way to simulate the code outside of solidcam, using the exported Gcode files, for verification before taking them to the machine?

Does the postprocessor support face and milling operations from solidcam? (those kind of operations are the ones I'm using)

What is the difference between using the Mach3_4X and Mach3_4Y machines?

Thanks in advance for any help! :)

**Comment by rvega** [comment]
Also, when changing the machine of my cam part project, solidcam is asking me to convert some drill cycles types as seen in the following screenshots. Please advise.

![1](https://cloud.githubusercontent.com/assets/37172/24923008/d1fe70a2-1eb5-11e7-9128-dd96115df220.png)
![2](https://cloud.githubusercontent.com/assets/37172/24923009/d20c145a-1eb5-11e7-9e45-686df5f1ca1a.png)

**Comment by rvega** [comment]
One more... What is the "trace level" asked when outputting the Gcode?

Thanks!

**Comment by rvega** [comment]
I finally figured out things by following tutorials and experimenting... closing

**Comment by teodoryantcheff** [comment]
Been really busy as of lately, hence long time no reply... Let me know if you still have questions I will try to help.
X and Y versions of the post I made for machine that have their 4th, rotary (A) axis parallel to either the X or the Y axis of the machine.... I don't think this will make a difference to your usecase.
