### ISSUE TITLE
Spindle Direction

### ISSUE THREAD

**Issue by biqut2** [teodoryantcheff/SolidCam-Mach3-Post#7]
In the following code the directions are inverted. M3 is CW and M4 is CCW.

@start_tool
    if tool_direction eq CW then
        mcode = 4
    else              ;  CCW
        mcode = 3
    endif

    {nb, 'S'spin:integer_def_f, ' M'mcode}
    {nb, 'M8'}
endp

**Comment by teodoryantcheff** [comment]
#8
