### ISSUE TITLE
Vmid adjust for mill turn options

### ISSUE THREAD

**Issue by Martinlipo** [teodoryantcheff/SolidCam-Mach3-Post#9]
Is not an Issue, just a contribution. I change the controller definition, defined parametes and working style in the VMID file. Now can do a mill-turn operation in solidcam. Work fine for me in my cnc. Please check it. Thanks!

PD: sorry for my bad english, I´m from Argentina.

[Mach3_4X_Y.zip](https://github.com/teodoryantcheff/SolidCam-Mach3-Post/files/2050446/Mach3_4X_Y.zip)

**Comment by teodoryantcheff** [comment]
Will do soon. BTW I was in Buenos Aires just a few months ago. You guys are cool! :) Cheers !
